"""
Week 4 P2/P3: three-language MGSM baseline with REAL model calls.

Every prediction in the output comes from a live API call made by this
script -- nothing is hard-coded, and deleting results/ and re-running
regenerates everything from data/mgsm_trilingual_sample.json (itself
regenerated by src/fetch_mgsm_trilingual.py from the official dataset).

Same prompt template for every language, same model, one call per
(question, language). Temperature is NOT sent: gpt-5.6-sol rejects an
explicit temperature=0 ("only the default (1) value is supported"), so the
plan's temperature-0 requirement cannot be met with this model. That fact is
recorded in every output row and in the run manifest rather than hidden.

Usage:
    python src/run_mgsm_trilingual.py --n-items 5 --tag smoke   # small test
    python src/run_mgsm_trilingual.py                           # full 50 x 3
"""
import argparse
import json
import os
import platform
import re
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import DATA_DIR, PROJECT_ROOT, RESULTS_DIR
from mgsm_scoring import _selftest, is_correct, parse_prediction

LANGS = ["en", "es", "ja"]
LANG_NAMES = {"en": "English", "es": "Spanish", "ja": "Japanese"}

PROMPT_TEMPLATE = (
    "Solve the following math problem carefully. Return the final answer on the last line "
    "in this format: FINAL ANSWER: <number>\n\nProblem: {question}"
)
TEMPERATURE_NOTE = "not set (model only supports its default; explicit temperature=0 is rejected)"
MAX_ATTEMPTS = 3
MAX_RATE_LIMIT_WAITS = 20  # per-minute caps are waited out, not counted as failed attempts

_quota_exhausted = threading.Event()


def load_env(path):
    if not os.path.exists(path):
        return
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                os.environ.setdefault(key.strip(), value.strip())


def call_model(client, model, prompt):
    """One real chat-completion call with bounded retries on transient errors.
    Returns a dict of raw results; never raises."""
    import openai

    last_error = ""
    attempt = 0
    rate_limit_waits = 0
    while attempt < MAX_ATTEMPTS:
        attempt += 1
        if _quota_exhausted.is_set():
            return {"raw_output": "", "error_message": "skipped: API credits exhausted earlier in this run"}
        try:
            resp = client.chat.completions.create(model=model, messages=[{"role": "user", "content": prompt}])
            usage = resp.usage
            details = getattr(usage, "completion_tokens_details", None)
            return {
                "raw_output": resp.choices[0].message.content or "",
                "model_returned": resp.model,
                "finish_reason": resp.choices[0].finish_reason,
                "prompt_tokens": usage.prompt_tokens,
                "completion_tokens": usage.completion_tokens,
                "reasoning_tokens": getattr(details, "reasoning_tokens", None),
                "error_message": "",
            }
        except (openai.RateLimitError, openai.APIStatusError) as exc:
            last_error = f"{type(exc).__name__}: {exc}"
            if "insufficient_quota" in str(exc) or "credit_balance_exhausted" in str(exc):
                _quota_exhausted.set()
                break
            if isinstance(exc, openai.BadRequestError) or isinstance(exc, openai.AuthenticationError):
                break  # retrying an invalid request cannot help
            if "rate_limit_exceeded" in str(exc) and rate_limit_waits < MAX_RATE_LIMIT_WAITS:
                # per-minute cap: wait as long as the server says (it is not a failed attempt)
                rate_limit_waits += 1
                attempt -= 1
                match = re.search(r"try again in (\d+(?:\.\d+)?)s", str(exc))
                time.sleep(float(match.group(1)) + 1 if match else 20)
                continue
        except (openai.APIConnectionError, openai.APITimeoutError) as exc:
            last_error = f"{type(exc).__name__}: {exc}"
        time.sleep(2 ** attempt)
    return {"raw_output": "", "error_message": last_error}


def run_one(args_tuple):
    client, model, item, lang = args_tuple
    question = item["questions"][lang]
    prompt = PROMPT_TEMPLATE.format(question=question)
    timestamp = datetime.now(timezone.utc).isoformat()
    result = call_model(client, model, prompt)

    raw_output = result["raw_output"]
    if result["error_message"]:
        prediction, method, correct = None, "none", None
    else:
        prediction, method = parse_prediction(raw_output)
        correct = is_correct(prediction, item["gold_answer"])

    return {
        "question_id": item["id"],
        "language": lang,
        "question": question,
        "gold_answer": item["gold_answer"],
        "prompt": prompt,
        "raw_output": raw_output,
        "parsed_prediction": prediction,
        "parse_method": method,
        "correct": correct,
        "model": model,
        "model_returned": result.get("model_returned", ""),
        "temperature": TEMPERATURE_NOTE,
        "timestamp": timestamp,
        "error_message": result["error_message"],
        "finish_reason": result.get("finish_reason", ""),
        "prompt_tokens": result.get("prompt_tokens"),
        "completion_tokens": result.get("completion_tokens"),
        "reasoning_tokens": result.get("reasoning_tokens"),
    }


def summarize(df):
    rows = []
    for lang in LANGS:
        sub = df[df["language"] == lang]
        answered = sub[sub["correct"].notna()]
        rows.append({
            "language": lang,
            "language_name": LANG_NAMES[lang],
            "n_trials": len(sub),
            "n_api_errors": int(sub["error_message"].astype(bool).sum()),
            "n_answered": len(answered),
            "n_correct": int(answered["correct"].astype(bool).sum()),
            "accuracy": round(float(answered["correct"].astype(bool).mean()), 4) if len(answered) else None,
            "n_fallback_parse": int((sub["parse_method"] == "fallback_last_number").sum()),
            "n_no_number": int((sub["parse_method"] == "none").sum() - sub["error_message"].astype(bool).sum()),
        })
    return pd.DataFrame(rows)


def main():
    parser = argparse.ArgumentParser(description="Three-language MGSM baseline with real API calls.")
    parser.add_argument("--data", default=os.path.join(DATA_DIR, "mgsm_trilingual_sample.json"))
    parser.add_argument("--n-items", type=int, default=None, help="use only the first N shared items (small test)")
    parser.add_argument("--tag", default="", help="suffix for output filenames, e.g. 'smoke'")
    parser.add_argument("--model", default=None, help="defaults to OPENAI_MODEL from .env")
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--resume", action="store_true",
                        help="keep successful records already in this run's JSONL log verbatim and re-call only "
                             "the failed ones (needed because the default temperature makes a full re-run non-identical)")
    args = parser.parse_args()

    _selftest()  # fail fast if the scoring code is broken
    load_env(os.path.join(PROJECT_ROOT, ".env"))
    model = args.model or os.environ.get("OPENAI_MODEL")
    if not os.environ.get("OPENAI_API_KEY") or not model:
        raise SystemExit("Set OPENAI_API_KEY and OPENAI_MODEL (see .env.example) before running.")

    import openai
    client = openai.OpenAI(api_key=os.environ["OPENAI_API_KEY"], timeout=120, max_retries=0)

    with open(args.data, encoding="utf-8") as f:
        dataset = json.load(f)
    items = dataset["items"][: args.n_items] if args.n_items else dataset["items"]

    prefix = "mgsm_trilingual" + (f"_{args.tag}" if args.tag else "")
    os.makedirs(RESULTS_DIR, exist_ok=True)
    log_path_prev = os.path.join(RESULTS_DIR, f"{prefix}_log.jsonl")

    reused = {}
    if args.resume and os.path.exists(log_path_prev):
        with open(log_path_prev, encoding="utf-8") as f:
            for line in f:
                rec = json.loads(line)
                if not rec["error_message"]:
                    reused[(rec["question_id"], rec["language"])] = rec

    all_keys = [(item["id"], lang) for item in items for lang in LANGS]
    tasks = [(client, model, item, lang) for item in items for lang in LANGS if (item["id"], lang) not in reused]
    print(f"{len(all_keys)} (question, language) pairs; reusing {len(reused)} existing successful records, "
          f"making {len(tasks)} real API calls with model {model}...")
    started = datetime.now(timezone.utc)
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        new_records = {(r["question_id"], r["language"]): r for r in pool.map(run_one, tasks)}
    finished = datetime.now(timezone.utc)
    records = [reused.get(k) or new_records[k] for k in all_keys]

    df = pd.DataFrame(records)

    full_path = os.path.join(RESULTS_DIR, f"{prefix}_full.csv")
    errors_path = os.path.join(RESULTS_DIR, f"{prefix}_errors.csv")
    log_path = os.path.join(RESULTS_DIR, f"{prefix}_log.jsonl")
    summary_path = os.path.join(RESULTS_DIR, f"{prefix}_language_summary.csv")
    pivot_path = os.path.join(RESULTS_DIR, f"{prefix}_correct_by_question.csv")
    meta_path = os.path.join(RESULTS_DIR, f"{prefix}_manifest.json")

    df.to_csv(full_path, index=False)
    # error table: wrong answers, API failures, and answers that needed the fallback parser
    flagged = df[(df["correct"] == False) | df["correct"].isna() | (df["parse_method"] != "final_answer_line")]  # noqa: E712
    flagged.to_csv(errors_path, index=False)
    with open(log_path, "w", encoding="utf-8") as f:  # overwritten each run: the log always matches this run's CSV
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")

    summary = summarize(df)
    summary.to_csv(summary_path, index=False)
    pivot = df.pivot(index="question_id", columns="language", values="correct")[LANGS]
    pivot.to_csv(pivot_path)

    manifest = {
        "started_utc": started.isoformat(),
        "finished_utc": finished.isoformat(),
        "model_requested": model,
        "models_returned": sorted(set(df["model_returned"].dropna()) - {""}),
        "temperature": TEMPERATURE_NOTE,
        "prompt_template": PROMPT_TEMPLATE,
        "n_questions": len(items),
        "languages": LANGS,
        "n_calls_this_invocation": len(tasks),
        "n_records_reused_from_previous_invocation": len(reused),
        "workers": args.workers,
        "data_file": os.path.relpath(args.data, PROJECT_ROOT),
        "python": platform.python_version(),
        "openai_sdk": openai.__version__,
    }
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    print("\n=== Language summary ===")
    print(summary.to_string(index=False))
    both_wrong = pivot[(pivot == False).sum(axis=1) >= 2]  # noqa: E712
    print(f"\nQuestions wrong in >=2 languages: {len(both_wrong)}")
    print(f"Wrote: {full_path}\n       {errors_path}\n       {log_path}\n       {summary_path}\n       {pivot_path}\n       {meta_path}")


if __name__ == "__main__":
    main()
